---
- name: Obtener información del sistema y paquetes
  hosts: all
  become: true
  gather_facts: true

  vars:
    salida_dir: "/tmp/ansible_info"
    archivo_csv: "{{ salida_dir }}/{{ inventory_hostname }}.csv"

  tasks:

    - name: Crear carpeta local para guardar los CSV
      delegate_to: localhost
      run_once: true
      file:
        path: "{{ salida_dir }}"
        state: directory
        mode: '0755'

    - name: Recolectar información del sistema
      set_fact:
        datos_sistema: |
          Hostname,Distribucion,Version,Kernel,Arquitectura
          {{ ansible_hostname }},{{ ansible_distribution }},{{ ansible_distribution_version }},{{ ansible_kernel }},{{ ansible_architecture }}

    - name: Obtener paquetes instalados (Debian)
      shell: dpkg-query -W -f='${binary:Package},${Version}\n'
      register: paquetes
      when: ansible_os_family == "Debian"

    - name: Obtener paquetes instalados (RedHat)
      shell: rpm -qa --qf '%{NAME},%{VERSION}-%{RELEASE}\n'
      register: paquetes
      when: ansible_os_family == "RedHat"

    - name: Guardar resultados en archivo CSV temporal en el host remoto
      copy:
        dest: "/tmp/{{ inventory_hostname }}_info.csv"
        content: |
          {{ datos_sistema }}
          Paquete,Version
          {{ paquetes.stdout }}

    - name: Copiar CSV desde host remoto a máquina controladora
      fetch:
        src: "/tmp/{{ inventory_hostname }}_info.csv"
        dest: "{{ salida_dir }}/"
        flat: true

    - name: Eliminar archivo CSV temporal del host remoto
      file:
        path: "/tmp/{{ inventory_hostname }}_info.csv"
        state: absent
