---
- name: IOC Deep Scan on Local Server (SOA/OSB/BPM/WebLogic)
  hosts: all
  connection: local
  become: yes

  vars:
    # IoCs de dominio y rutas completas
    iocs:
      - "encr.pw"
      - "enasui.com"
      - "mdowny11.cfd"

    full_iocs:
      - "encr.pw/eKn5j"
      - "encr.pw/bancaFINDOMESTIC"
      - "enasui.com/area_comedor_new/js/jspdf.jquery.js"
      - "encr.pw/2022irstaxrefundclaim"
      - "encr.pw/sella-hype-web"
      - "encr.pw/32IYY"
      - "encr.pw/hype-aggiorna-web"

    domains:
      - PROD_SOA_DOMAIN
      - PROD_OSB_DOMAIN
      - PROD_BPM_DOMAIN

    base_path: "/u01/app/oracle/admin/domains"
    log_path: "/u01/app/oracle/admin/logs"
    report_file: "/tmp/ioc_report_local_{{ ansible_hostname }}.log"

  tasks:

    - name: Crear archivo vacío de reporte
      copy:
        dest: "{{ report_file }}"
        content: "Reporte IoC Deep Scan - {{ ansible_hostname }}\n\n"

    ###########################################################################
    # 1. SCAN BÁSICO DE LOGS
    ###########################################################################

    - name: Buscar IoCs de dominios base en logs
      shell: |
        grep -RinE "{{ iocs | join('|') }}" {{ log_path }}/* 2>/dev/null || true
      register: log_basic

    - name: Buscar IoCs de rutas completas en logs
      shell: |
        grep -RinE "{{ full_iocs | join('|') }}" {{ log_path }}/* 2>/dev/null || true
      register: log_full

    - name: Insertar resultados en reporte
      lineinfile:
        path: "{{ report_file }}"
        insertafter: EOF
        line: |
          =============================
          [LOG SCAN - DOMINIOS]
          {{ log_basic.stdout }}
          -----------------------------
          [LOG SCAN - RUTAS COMPLETAS]
          {{ log_full.stdout }}
          =============================

    ###########################################################################
    # 2. SCAN CONFIGURACIONES (config.xml, jdbc, osb, bpm, soa)
    ###########################################################################

    - name: Escanear configuraciones WebLogic (dominios base)
      shell: |
        grep -RinE "{{ iocs | join('|') }}" {{ base_path }} 2>/dev/null || true
      register: config_basic

    - name: Escanear rutas completas en configuración
      shell: |
        grep -RinE "{{ full_iocs | join('|') }}" {{ base_path }} 2>/dev/null || true
      register: config_full

    - name: Agregar resultados de configuración al reporte
      lineinfile:
        path: "{{ report_file }}"
        insertafter: EOF
        line: |
          =============================
          [CONFIG SCAN - DOMINIOS]
          {{ config_basic.stdout }}
          -----------------------------
          [CONFIG SCAN - RUTAS COMPLETAS]
          {{ config_full.stdout }}
          =============================

    ###########################################################################
    # 3. SCAN DE DEPLOYMENTS (EAR, WAR, JAR, composites, OSB)
    ###########################################################################

    - name: Escanear artefactos (EAR/WAR/JAR) dentro del dominio
      shell: |
        for domain in {{ domains | join(' ') }}; do
          find {{ base_path }}/$domain -name "*.jar" -o -name "*.war" -o -name "*.ear" 2>/dev/null | while read file; do
            unzip -p "$file" | grep -Ei "{{ iocs | join('|') }}" && echo "IOC en $file"
          done
        done
      register: artifact_scan

    - name: Agregar artefactos al reporte
      lineinfile:
        path: "{{ report_file }}"
        insertafter: EOF
        line: |
          =============================
          [DEPLOYMENT SCAN - EAR/WAR/JAR]
          {{ artifact_scan.stdout }}
          =============================

    ###########################################################################
    # 4. TMP RUNTIME DE WEBLOGIC (MUY IMPORTANTE)
    ###########################################################################

    - name: Escanear tmp/_WL_user (runtime real de servicios)
      shell: |
        grep -RinE "{{ iocs | join('|') }}" {{ base_path }}/*/servers/*/tmp/_WL_user 2>/dev/null || true
      register: tmp_scan

    - name: Agregar tmp runtime al reporte
      lineinfile:
        path: "{{ report_file }}"
        insertafter: EOF
        line: |
          =============================
          [RUNTIME /tmp/_WL_user]
          {{ tmp_scan.stdout }}
          =============================

    ###########################################################################
    # 5. PROCESOS JAVA (SOA/OSB/BPM)
    ###########################################################################

    - name: Detectar procesos Java activos WebLogic
      shell: ps -ef | grep java | grep -v grep
      register: java_proc

    - name: Agregar procesos Java al reporte
      lineinfile:
        path: "{{ report_file }}"
        insertafter: EOF
        line: |
          =============================
          [JAVA PROCESSES]
          {{ java_proc.stdout }}
          =============================

    ###########################################################################
    # 6. DNS LIVE SCAN (QUÉ PID MANDA LAS CONSULTAS)
    ###########################################################################

    - name: Captura en vivo DNS (si existe tcpdump)
      shell: |
        if command -v tcpdump >/dev/null; then
          timeout 6 tcpdump -n -i any port 53 2>/dev/null | grep -Ei "{{ iocs | join('|') }}"
        else
          echo "tcpdump no instalado"
        fi
      register: dns_scan

    - name: Agregar DNS al reporte
      lineinfile:
        path: "{{ report_file }}"
        insertafter: EOF
        line: |
          =============================
          [DNS LIVE SCAN]
          {{ dns_scan.stdout }}
          =============================

    ###########################################################################
    # FIN
    ###########################################################################

    - name: Mostrar ubicación del reporte final
      debug:
        msg: "Reporte generado en: {{ report_file }}"
