---
- name: Instalar Lumu Linux Agent en Ubuntu/Debian
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Actualizar caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar dependencias necesarias
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Crear directorio /etc/apt/keyrings si no existe
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargar y guardar clave GPG de Lumu (evitar duplicados)
      shell: |
        wget -q -O - https://packages.lumu.io/ubuntu/ubuntu.pub.key | gpg --dearmor -o /etc/apt/keyrings/lumu.gpg
      args:
        creates: /etc/apt/keyrings/lumu.gpg

    - name: Dar permisos de lectura a la clave
      file:
        path: /etc/apt/keyrings/lumu.gpg
        mode: '0644'

    - name: "Obtener codename del sistema (ej: jammy, focal)"
      shell: . /etc/os-release && echo "$VERSION_CODENAME"
      register: version_codename
      changed_when: false

    - name: Agregar repositorio de Lumu
      copy:
        dest: /etc/apt/sources.list.d/lumu.list
        content: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/lumu.gpg] https://packages.lumu.io/ubuntu/{{ version_codename.stdout }} {{ version_codename.stdout }} stable

    - name: Actualizar repositorios
      apt:
        update_cache: yes

    - name: Instalar el agente Lumu
      apt:
        name: lumu-linux-agent
        state: present
