---
- name: Recopilar información de CPU, RAM y Disco Duro
  hosts: all
  gather_facts: yes
  tasks:
    - name: Obtener información de la CPU
      ansible.builtin.command: lscpu
      register: cpu_info

    - name: Mostrar información de la CPU
      ansible.builtin.debug:
        var: cpu_info.stdout_lines

    - name: Obtener información de la RAM
      ansible.builtin.command: free -h
      register: ram_info

    - name: Mostrar información de la RAM
      ansible.builtin.debug:
        var: ram_info.stdout_lines

    - name: Obtener información del disco duro
      ansible.builtin.command: df -h
      register: disk_info

    - name: Mostrar información del disco duro
      ansible.builtin.debug:
        var: disk_info.stdout_lines
