---
- name: Compilar e instalar sudo 1.9.17p1 en Ubuntu y Oracle Linux
  hosts: all
  become: true
  become_user: root
  vars:
    sudo_version: "1.9.17p1"
    sudo_url: "https://www.sudo.ws/dist/sudo-1.9.17p1.tar.gz"

  tasks:

    - name: Recopilar información del sistema operativo
      ansible.builtin.setup:
        gather_subset:
          - os_family
          - distribution

    #### Descargar, compilar e instalar sudo ####
    - name: Crear carpeta temporal para compilación
      ansible.builtin.file:
        path: /tmp/sudo_build
        state: directory
        mode: '0755'

    - name: Descargar sudo {{ sudo_version }}
      ansible.builtin.get_url:
        url: "{{ sudo_url }}"
        dest: "/tmp/sudo_build/sudo-{{ sudo_version }}.tar.gz"

    - name: Extraer código fuente de sudo
      ansible.builtin.unarchive:
        src: "/tmp/sudo_build/sudo-{{ sudo_version }}.tar.gz"
        dest: /tmp/sudo_build
        remote_src: yes

    - name: Compilar e instalar sudo
      ansible.builtin.shell: |
        cd /tmp/sudo_build/sudo-{{ sudo_version }}
        ./configure --prefix=/usr/local
        make
        make install
      args:
        executable: /bin/bash

    #### Respaldar y reemplazar binario de sudo ####
    - name: Hacer respaldo de sudo actual
      ansible.builtin.copy:
        src: /usr/bin/sudo
        dest: /usr/bin/sudo.bak
        remote_src: yes
        backup: yes

    - name: Reemplazar binario de sudo por el compilado
      ansible.builtin.copy:
        src: /usr/local/bin/sudo
        dest: /usr/bin/sudo
        remote_src: yes
        mode: '0755'

    #### Verificación final ####
    - name: Verificar versión de sudo instalada
      ansible.builtin.command: sudo -V
      register: sudo_ver
      changed_when: false

    - name: Mostrar versión de sudo
      ansible.builtin.debug:
        var: sudo_ver.stdout_lines
