---
- name: Actualizar parches de seguridad en servidores Ubuntu y guardar resultados
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: Actualizar la lista de paquetes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar solo actualizaciones de seguridad
      ansible.builtin.apt:
        upgrade: dist
        allow_unauthenticated: no
      register: upgrade_result

    - name: Guardar el resultado de las actualizaciones en un archivo
      ansible.builtin.copy:
        dest: "/tmp/actualizacion_seguridad_{{ inventory_hostname }}.txt"
        content: |
          Resultados de la actualización de seguridad para {{ inventory_hostname }}:
          Fecha: {{ ansible_date_time.date }} Hora: {{ ansible_date_time.time }}
          
          Resultado de la actualización:
          {{ upgrade_result | to_nice_json }}
        mode: '0644'

    - name: Comprobar si es necesario reiniciar el sistema
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_needed

    - name: Reiniciar el servidor si es necesario
      ansible.builtin.reboot:
      when: reboot_needed.stat.exists
