---
- name: Actualizar parches de seguridad en servidores Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Actualizar la lista de paquetes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar solo actualizaciones de seguridad
      ansible.builtin.apt:
        upgrade: dist
        allow_unauthenticated: no

    - name: Comprobar si es necesario reiniciar el sistema
      ansible.builtin.command: /usr/bin/needs-restarting
      register: reboot_needed
      ignore_errors: yes
      changed_when: reboot_needed.rc == 1

    - name: Reiniciar el servidor si es necesario
      ansible.builtin.reboot:
      when: reboot_needed.rc == 1
