---
- name: Actualizar parches de seguridad en servidores Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Actualizar la lista de paquetes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar solo actualizaciones de seguridad
      ansible.builtin.apt:
        upgrade: dist
        allow_unauthenticated: no

    - name: Comprobar si es necesario reiniciar el sistema
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_needed

    - name: Reiniciar el servidor si es necesario
      ansible.builtin.reboot:
      when: reboot_needed.stat.exists

