---
- name: Obtener usuarios del sistema operativo Oracle y guardar en XML
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    salida_local: "/tmp/usuarios_sistema.xml"

  tasks:
    - name: Obtener lista completa de usuarios del sistema
      command: cat /etc/passwd
      register: passwd_contenido

    - name: Obtener miembros del grupo sudo o wheel (administradores)
      shell: getent group sudo || getent group wheel
      register: grupo_admin

    - name: Crear reporte temporal en el nodo remoto
      copy:
        dest: /tmp/usuarios_tmp.txt
        content: |
          ==== Usuarios del sistema ====
          {{ passwd_contenido.stdout }}

          ==== Grupo de administradores ====
          {{ grupo_admin.stdout }}

    - name: Copiar archivo temporal desde el servidor remoto
      fetch:
        src: /tmp/usuarios_tmp.txt
        dest: /tmp/usuarios_tmp_{{ inventory_hostname }}.txt
        flat: yes

- name: Consolidar resultados en el servidor de Ansible
  hosts: localhost
  gather_facts: no
  vars:
    salida_local: "/tmp/usuarios_sistema.xml"
  tasks:
    - name: Generar archivo XML consolidado
      copy:
        dest: "{{ salida_local }}"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <servidores>
          {% for host in hostvars %}
            {% if 'usuarios_tmp_' ~ host in lookup('fileglob', '/tmp/usuarios_tmp_*') %}
            <servidor nombre="{{ host }}">
              <usuarios>
              {{ lookup('file', '/tmp/usuarios_tmp_' ~ host ~ '.txt') | indent(4) }}
              </usuarios>
            </servidor>
            {% endif %}
          {% endfor %}
          </servidores>
    - name: Mostrar ubicación del XML generado
      debug:
        msg: "Archivo XML generado en {{ salida_local }}"
