---
- name: Consultar usuarios del sistema sin escribir en remoto
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Obtener lista de usuarios del sistema
      command: cat /etc/passwd
      register: usuarios_sistema

    - name: Obtener grupo de administradores
      shell: getent group sudo || getent group wheel
      register: grupo_admin
      failed_when: false

    - name: Acumular datos en el controlador
      delegate_to: localhost
      run_once: false
      set_fact:
        reporte_usuarios: "{{ (reporte_usuarios | default({})) | combine({inventory_hostname: {'usuarios': usuarios_sistema.stdout, 'admin': grupo_admin.stdout}}) }}"


- name: Generar archivo XML consolidado en el controlador
  hosts: localhost
  gather_facts: no
  vars:
    salida_local: "/tmp/usuarios_sistema.xml"

  tasks:
    - name: Crear XML desde plantilla Jinja2
      template:
        src: usuarios_sistema.xml.j2
        dest: "{{ salida_local }}"

    - name: Mostrar ubicación del XML generado
      debug:
        msg: "Archivo XML generado correctamente en {{ salida_local }}"
