---
- name: Consultar usuarios del sistema sin escribir en remoto
  hosts: oracle_servers
  gather_facts: no
  become: yes

  tasks:
    - name: Obtener lista de usuarios del sistema
      command: cat /etc/passwd
      register: usuarios_sistema

    - name: Obtener grupo de administradores
      shell: getent group sudo || getent group wheel
      register: grupo_admin
      failed_when: false

    - name: Enviar datos al controlador
      delegate_to: localhost
      run_once: false
      set_fact:
        reporte_usuarios: "{{ (reporte_usuarios | default({})) | combine({inventory_hostname: {'usuarios': usuarios_sistema.stdout, 'admin': grupo_admin.stdout}}) }}"

- name: Generar XML consolidado en el controlador
  hosts: localhost
  gather_facts: no
  vars:
    salida_local: "/tmp/usuarios_sistema.xml"

  tasks:
    - name: Crear XML usando plantilla segura
      copy:
        dest: "{{ salida_local }}"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <servidores>
          {% for host, datos in reporte_usuarios.items() %}
            <servidor nombre="{{ host }}">
              <usuarios><![CDATA[{{ datos.usuarios | replace(']]>', ']]]]><![CDATA[>') }}]]></usuarios>
              <administradores><![CDATA[{{ datos.admin | default('') | replace(']]>', ']]]]><![CDATA[>') }}]]></administradores>
            </servidor>
          {% endfor %
