---
- name: Consultar usuarios del sistema (sin escribir en remoto)
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Obtener lista de usuarios del sistema
      command: cat /etc/passwd
      register: usuarios_sistema

    - name: Obtener grupo de administradores
      shell: getent group sudo || getent group wheel
      register: grupo_admin
      failed_when: false

    - name: Guardar datos de cada host en variables locales
      set_fact:
        reporte_usuarios: "{{ (hostvars.localhost.reporte_usuarios | default({})) | combine({inventory_hostname: {'usuarios': usuarios_sistema.stdout, 'admin': grupo_admin.stdout}}) }}"
      delegate_to: localhost
      run_once: false


- name: Generar archivo XML consolidado en el servidor de Ansible
  hosts: localhost
  gather_facts: no
  vars:
    salida_local: "/tmp/usuarios_sistema.xml"

  tasks:
    - name: Crear XML con los datos recolectados
      copy:
        dest: "{{ salida_local }}"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <servidores>
          {% for host, datos in reporte_usuarios.items() %}
            <servidor nombre="{{ host }}">
              <usuarios><![CDATA[
{{ datos.usuarios }}
              ]]></usuarios>
              <administradores><![CDATA[
{{ datos.admin }}
              ]]></administradores>
            </servidor>
          {% endfor %}
          </servidores>

    - name: Mostrar ruta del XML generado
      debug:
        msg: "Archivo XML generado correctamente en {{ salida_local }}"
