---

- name: Instalar y configurar Zabbix Agent en Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Agregar el repositorio de Zabbix
      apt:
        deb: "deb https://repo.zabbix.com/zabbix/6.0/ubuntu $(lsb_release -cs) main"
        state: present
        update_cache: yes

    - name: Agregar la clave GPG de Zabbix
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    - name: Instalar Zabbix Agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Configurar Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^{{ item.key }}='
        line: "{{ item.key }}={{ item.value }}"
      with_items:
        - { key: 'Server', value: '172.16.120.231' }
        - { key: 'ServerActive', value: '172.16.120.231' }
        - { key: 'Hostname', value: '{{ inventory_hostname }}' }

    - name: Reiniciar Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes
